/**
 * WARNING: Example file used for refactoring-tool demos. Avoid manual edits.
 *
 * Extracted types and interfaces
 * Auto-generated by ts-morph refactoring script
 */

export interface User {
  id: string;
  name: string;
  email: string;
  role: 'admin' | 'user' | 'guest';
  status: 'active' | 'inactive';
  createdAt: string;
}
export interface FormData {
  name: string;
  email: string;
  role: 'admin' | 'user' | 'guest';
}
export interface ValidationErrors {
  name?: string;
  email?: string;
  role?: string;
}
