/**
 * Extracted utility functions
 * Auto-generated by ts-morph refactoring script
 */

import type { FormData, ValidationErrors } from './UserManagementDashboard.types';

export const validateForm = (data: FormData): ValidationErrors => {
    const errors: ValidationErrors = {};
    
    if (!data.name.trim()) {
      errors.name = 'Name is required';
    } else if (data.name.length < 2) {
      errors.name = 'Name must be at least 2 characters';
    } else if (data.name.length > 50) {
      errors.name = 'Name must be less than 50 characters';
    }
    
    if (!data.email.trim()) {
      errors.email = 'Email is required';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) {
      errors.email = 'Invalid email format';
    }
    
    if (!data.role) {
      errors.role = 'Role is required';
    }
    
    return errors;
  };

export const getRoleBadgeColor = (role: string): "#ff6b6b" | "#4ecdc4" | "#95a5a6" | "#7f8c8d" => {
    switch (role) {
      case 'admin': return '#ff6b6b';
      case 'user': return '#4ecdc4';
      case 'guest': return '#95a5a6';
      default: return '#7f8c8d';
    }
  };

export const getStatusBadgeColor = (status: string): "#2ecc71" | "#e74c3c" => {
    return status === 'active' ? '#2ecc71' : '#e74c3c';
  };

export const formatDate = (dateString: string): string => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };